### ISSUE TITLE
Question: Why these]?????

### ISSUE THREAD

**Issue by Ratatouilledummie** [NVIDIA/egl-gbm#2]
is not more easy work in Mesa3D drivers official for Nvidia instead a proprietary and buggy driver????? i understand the problem about IP and some functions disabled in driver for more profit. But is not more easy implement all these stuffs in a nvidia minimal proprietary driver with NVCODEC with others IP, and all the OpenGL,GLX,EGL,GBM,VAAPI and other stuffs in Mesa Gallium3D driver?????

**Comment by cubanismo** [comment]
Closing.
